project:
  type: website

website:
  title: "Sesiunea de comunicări științifice studențești"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: manuscript.qmd
        text: Manuscript
      - href: presentation.qmd
        text: Presentation
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



